Refactor - Resource References + Constructing ARM Functions
hamlet-io/engine-plugin-azure pull request #202
Opened 2020-09-19 08:54 UTC by RossMurr4y

Description
Implements the following changes, enabled by #200
* `@armResource` refactored to implement scopes, which will nest resources as necessary.
* Added `constructArmOutputsFromMappings` function which creates appropriately scoped outputs
* `getReference()` for the Azure provider completely reworked and drastically simplified
* Same for `getChildReference()` previously `getSubReference()`
* Standardised the approach to constructing  ARM functions - can now create raw (no boilerplate) functions and standard functions as needed, nesting them to enable more complex functionality that is occasionally required
* Completed the transition from “pseudo” resource “types” to “pseudo” as a scope
* Enabled resource type name spacing, where multiple resources under the same provider use the same name. Namespacing allows for the definition of unique names (i.e `service:apis` and `product:apis`, whilst ensuring the provider-defined type is accessible. 
	* Resource naming updated to only use the last namespace

### Additional Housekeeping Changes
* Cleaned up numerous unused functions, macros, resources and resourceProfiles
* added some missing outputs that were being implemented by other means incorrectly
* moved some discovered resource naming out of setup and into state

## Motivation and Context

Closes #195
Closes #196 

## How Has This Been Tested?

Local template generation

## Types of changes

- [ ] [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] [x] Refactor (non-breaking change which improves the structure or operation of the implementation)
- [ ] [ ] New feature (non-breaking change which adds functionality)
- [ ] [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Followup Actions

- [ ] requires #200 

## Checklist:

- [ ] [ ] My change requires a change to the [documentation](https://github.com/hamlet-io/docs).
- [ ] [ ] I have updated the documentation accordingly.
- [ ] [ ] I have added tests to cover my changes.
- [ ] [ ] All new and existing tests passed.
- [ ] [x] None of the above.

2020-09-20 23:20 UTC, ml019 requested changes
Overall this looks to clean up and simplify things.

Please ensure key core functions are well documented to assist ongoing maintenance.

2020-09-20 23:20 UTC, ml019 commented on azure/deploymentframeworks/arm/output.ftl
> +[#function constructArmOutputsFromMappings id name scope mappings=[]]
A few more comments please.

2020-09-21 01:23 UTC, RossMurr4y commented on azure/deploymentframeworks/arm/output.ftl
> +[#function constructArmOutputsFromMappings id name scope mappings=[]]
Have added some more, hopefully they make sense!

2020-11-02 04:06 UTC, roleyfoley commented
@RossMurr4y Looks like we have some new conflicts, would you mind resolving them?

2020-11-09 00:26 UTC, RossMurr4y commented
@roleyfoley  I've resolved the conflicts :)

2020-12-07 04:24 UTC, merged