Feat/static website hosting
hamlet-io/engine-plugin-azure pull request #245
Opened 2021-04-06 08:49 UTC by RossMurr4y

## Description

- sets the static web hosting property on the baseline storage account when an SPA is configured
- sets the index/404 pages defined on the CDN on an associated SPA's storage account
- minor tidy up of old code/comments

## Motivation and Context

Closes #183 

## How Has This Been Tested?

Tested locally, however still requires deploy testing as I don't currently have an SPA deployed for test purposes

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which improves the structure or operation of the implementation)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Followup Actions

- [x] None

## Checklist:

- [ ] My change requires a change to the [documentation](https://github.com/hamlet-io/docs).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] None of the above.

2021-04-07 00:24 UTC, roleyfoley requested changes

2021-04-07 00:24 UTC, roleyfoley commented on azure/components/baseline/setup.ftl
> +              [/#list]
This feels magic, might be better as an attribute on the baseline with a check done by the SPA to see if its enabled.

2021-04-07 00:24 UTC, roleyfoley commented on azure/components/baseline/setup.ftl
> +              [/#if]
Does this affect all storage blobs within the account?

2021-04-07 00:24 UTC, roleyfoley commented on azure/components/cdn/setup.ftl
> +                        [/#list]
How would this work if I had multiple SPA's under the same site? won't this override if this is applied to the storage account overall?

2021-04-07 00:24 UTC, roleyfoley commented on azure/components/cdn/setup.ftl
> +                        [/#list]
Also I would have thought this would be a configuration action as a rule on the Frontdoor rather than on the origin

2021-04-08 00:12 UTC, RossMurr4y commented
> How would this work if I had multiple SPA's under the same site? won't this override if this is applied to the storage account overall?

This question has raised a good point that the current SPA setup overall cannot support multiple SPA's at all - every one of them requires a blob store called `$web`, of which there can only be one per storage account. Currently SPA's are all configured to use the OpsData bucket in baseline, which prevents more than 1 from ever working.

This requires a refactor of the SPA overall, which will expose better ways of implementing the static website hosting feature. I'm going to cancel this PR and update the original ticket with this in mind.

2021-04-08 00:12 UTC, closed without merging